import { Inter } from "next/font/google";
import "./globals.css";
import MyNav from "./MyNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="myHeader">
          <MyNav />
        </header>
        <main className="myContent">
          {children}
        </main>
        <footer>
          <div className="myFooter">
            (c) 2024 by me
          </div>
        </footer>
      </body>
    </html >
  );
}
